/*

    OpenGL loader generated by glad 0.1.14a0 on Fri Jun  2 20:44:44 2017.

    Language/Generator: D
    Specification: gl
    APIs: gl=4.5
    Profile: core
    Extensions:
        GL_ARB_sparse_texture,
        GL_ARB_sparse_texture2,
        GL_ARB_sparse_texture_clamp
    Loader: True
    Local files: False
    Omit khrplatform: False

    Commandline:
        --profile="core" --api="gl=4.5" --generator="d" --spec="gl" --extensions="GL_ARB_sparse_texture,GL_ARB_sparse_texture2,GL_ARB_sparse_texture_clamp"
    Online:
        http://glad.dav1d.de/#profile=core&language=d&specification=gl&loader=on&api=gl%3D4.5&extensions=GL_ARB_sparse_texture&extensions=GL_ARB_sparse_texture2&extensions=GL_ARB_sparse_texture_clamp
*/

module glad.gl.all;


public import glad.gl.funcs;
public import glad.gl.ext;
public import glad.gl.enums;
public import glad.gl.types;
